---
grails:
  profile: web
  codegen:
    defaultPackage: app
  gorm:
    reactor:
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
environments:
  development:
    management:
      endpoints:
        enabled-by-default: true
        web:
          base-path: '/actuator'
          exposure:
            include: '*'
  production:
    management:
      endpoints:
        enabled-by-default: false

server:
  port: 8081

---
grails:
  cors:
    enabled: true
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      text: text/plain
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  username: cristif
  password: cristif
  dbCreate: update
  url: jdbc:mysql://localhost:3306/newdb
  properties:
    defaultTransactionIsolation: 2

server:
  timezone: UTC